import = ["/home/shket/.config/alacritty/colors/rose-pine.toml", "/home/shket/.config/alacritty/extended-keys.toml"]

[cursor]
thickness = 0.2

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 14

[font.bold]
style = "Bold"

[font.italic]
style = "Regular"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_padding = true
opacity = 1

[[keyboard.bindings]]
chars = "\u001B[67;6u"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[67;6u"
key = "ะก"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "ะก"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "ะ"
mods = "Control|Shift"
