#!/bin/sh
#alias g='lazygit'
alias zsh-update-plugins="find "$ZSHPLUGINDIR/plugin" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

function duh {
    du -had1 $1 | sort -h
}
function duh2 {
    du -had2 $1 | sort -h
}
function duh3 {
    du -had3 $1 | sort -h
}

# Neovim
alias v='nvim'
# alias ve='nvim .'
alias vf="nvim -c 'Telescope find_files'"
alias vg="nvim -c 'Telescope live_grep_args'"
alias va="nvim -c \"normal! 'A\""
alias vl='nvim -c "execute \"normal! \<C-O>\""'
alias vdb="tmux rename-window DB; nvim -c 'DBUIToggle'"

# Tmux
alias t='tmux'
alias ta='tmux attach'

# Colorize output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls -Av --group-directories-first --color=auto'
alias l='ls -lApth'

# Navigation
function cd {
    builtin cd "$@" && ls
}
function z_alias {
    __zoxide_z "$@" && ls
}
function zi_alias {
    __zoxide_zi "$@" && ls
}
alias z=z_alias
alias zi=zi_alias
alias cdf='cd "$(fzf | xargs -0 dirname)"'

# Clipboard
alias clip='xclip -selection clipboard'
function cpass {
    echo -n $(pass $@) | xclip -selection clipboard
}

# Package manager
alias autoremove='pacman -Qdtq | sudo pacman -Rs -'

# Python
alias ipy=ipython

# Git
function gacp {
    git add .
    git commit -m "$@"
    git push
}

# Quick access
function todo {
    DIR=~/projects/markdown/main-notes
    FILE="TODOTODAY.md"
    cd $DIR
    tmux rename-window TODO
    nvim $FILE
}
function nvimcfg {
    DIR=~/.config/nvim
    cd $DIR
    tmux rename-window NVIM
    vf
}

# LLM
function webui-restart {
    docker rm -f open-webui 2> /dev/null
    docker run -d --gpus all \
        -e PORT=1144 --network=host \
        -v open-webui:/app/backend/data \
        --name open-webui \
        ghcr.io/open-webui/open-webui:cuda
}
function webui-stop {
    docker rm -f open-webui 2> /dev/null
}
function tabby-start {
    docker run -dt --gpus all \
        -e TABBY_WEBSERVER_JWT_TOKEN_SECRET='6a335735-3e9c-4afc-919d-e1e31c9b66e6' \
        -p 7488:8080 -v $HOME/.tabby:/data \
        --name tabby-ml \
        registry.tabbyml.com/tabbyml/tabby \
        serve --model CodeQwen-7B --device cuda
}
function tabby-attach {
    docker attach tabby-ml
}
function tabby-stop {
    docker rm -f tabby-ml 2> /dev/null
}
# --restart always \
