ZSHPLUGINDIR="$HOME/.local/share/zsh/plugins"

# General
unsetopt beep
setopt append_history
setopt hist_ignore_all_dups
setopt interactive_comments

# Navigation & Editing
autoload -U select-word-style
select-word-style bash

# Color variables
autoload -U colors && colors
eval $(dircolors)

# Completions
autoload -U compinit; compinit
zmodload zsh/complist
setopt menu_complete
_comp_options+=(globdots)
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Useful Functions
source "$ZDOTDIR/zsh-utils"
# Normal files to source
source "$ZDOTDIR/zsh-exports"
source "$ZDOTDIR/zsh-vim-mode"
source "$ZDOTDIR/zsh-aliases"
source "$ZDOTDIR/zsh-prompt"
source "$ZDOTDIR/zsh-keys"
source "$ZDOTDIR/zsh-colors"

# Plugins
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
