[colors.bright]
black = "0x6e6a86"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0xe0def4"
text = "0x191724"

[colors.hints.end]
background = "#26233a"
foreground = "#555169"

[colors.hints.start]
background = "#26233a"
foreground = "#6e6a86"

[colors.normal]
black = "0x26233a"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"
