require("ashket.cmp")
require("ashket.lsp")
require("ashket.null-ls")
require("ashket.treesitter")
require("ashket.telescope")
require("ashket.lualine")

require("ashket.nvim-tree")
require("ashket.aerial")
require("ashket.comment")
-- require("ashket.autopairs")
require("ashket.surround")
require("ashket.mini")
require("ashket.auto-save")

require("ashket.colors")
require("ashket.specific")
