#!/bin/bash

PYTHON3_LIB="lib/python3*/site-packages"
VS_STUBS="$HOME/.vscode/extensions/ms-python.vscode-pylance-*/dist/bundled"

# Copy VSCode stubs to Python site-packages
function cp_vs_stubs() {
    destination=$1/$PYTHON3_LIB
    if [ -d $VS_STUBS ]; then
        echo "reached inner"
        for stubs in $VS_STUBS/stubs $VS_STUBS/native-stubs; do
            cp -ru $stubs/* $destination
            echo "cp -ru $stubs/* $destination"
        done
    fi
}


while [[ $1 ]]; do
    case $1 in
        -v | --virtualenv)
            shift
            env_path="$1"
            cp_vs_stubs $env_path;;
        -h | --help | *)
            echo "Usage: ./cp_vs_stubs.sh [-v, --virtualenv | -h, --help]";;
    esac
    shift
done

