require("shket.cmp")
require("shket.lsp")
require("shket.null-ls")
require("shket.treesitter")
require("shket.telescope")
require("shket.lualine")

require("shket.nvim-tree")
require("shket.aerial")
require("shket.comment")
-- require("shket.autopairs")
require("shket.surround")
require("shket.mini")
require("shket.auto-save")

require("shket.colors")
require("shket.specific")
