require("plugins.colors")
require("plugins.tweaks")
require("plugins.git")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.diagnostic")
require("plugins.debug")
require("plugins.statusline")
require("plugins.tabs")
-- require("plugins.explorer")
require("plugins.symbols")
-- require("plugins.autopairs")
require("plugins.mini")
require("plugins.tmux")
require("plugins.jupyter")
require("plugins.indent")
require("plugins.dev")
require("plugins.treesitter")
require("plugins.telescope")
