#!/bin/sh
#alias g='lazygit'
alias zsh-update-plugins="find "$ZSHPLUGINDIR/plugin" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias duh='du -had1 | sort -rh'

# Neovim
alias v='nvim'
# alias ve='nvim .'
alias vf="nvim -c 'Telescope find_files'"
alias vg="nvim -c 'Telescope live_grep_args'"
alias va="nvim -c \"normal! 'A\""
alias vl='nvim -c "execute \"normal! \<C-O>\""'
alias vd="nvim -c 'DBUIToggle'"

# Tmux
alias t='tmux'
alias ta='tmux a -t 0'

# Colorize output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls -Av --group-directories-first --color=auto'
alias l='ls -lApthvr --group-directories-first --color=auto'

# Navigation
function cd {
    builtin cd "$@" && ls
}
function z_alias {
    __zoxide_z "$@" && ls
}
function zi_alias {
    __zoxide_zi "$@" && ls
}
alias z=z_alias
alias zi=zi_alias
alias fcdf='cd $(find . -type d -print | fzf)'

# Clipboard
alias clip='xclip -selection clipboard'
function cpass {
    echo -n $(pass $@) | xclip -selection clipboard
}

# Python
alias ipy=ipython
