#!/bin/sh

# History
HISTFILE="$HOME/.zsh_history"
HISTCONTROL=ignoredups
HISTSIZE=10000
SAVEHIST=10000

# Path
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$HOME/bin/statusbar:$PATH"
PATH="$HOME/.cargo/bin:$PATH"
# PATH="$HOME/.local/share/lua-language-server/bin:$PATH"
#PATH="$HOME/.local/share/deno/bin:$PATH"
PATH="/usr/local/go/bin:$PATH"
# PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
#PATH="$HOME/.go/bin:$PATH"

# Python
# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"

# Latex
#PATH="$HOME/.local/texlive/2022/bin/x86_64-linux:$PATH"
#MANPATH="$HOME/.local/texlive/2022/texmf-dist/doc/man"
#INFOPATH="$HOME/.local/texlive/2022/texmf-dist/doc/info"

# Packages
export NODE_PATH="/usr/local/lib/node_modules"
#export GOPATH="$HOME/.go"

# Man
export MANPAGER='nvim +Man!'

# God's tools
eval "$(zoxide init zsh)"

# Environment variables set everywhere
EDITOR="nvim"
TERMINAL="alacritty"
BROWSER="google-chrome"
