#!/bin/sh
#alias g='lazygit'
alias zsh-update-plugins="find "$ZSHPLUGINDIR/plugin" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias duh='du -had1 | sort -rh'

# Colorize output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls -Av --group-directories-first --color=auto'
function cd {
    builtin cd "$@" && ls
}
function z_alias {
    __zoxide_z "$@" && ls
}
function zi_alias {
    __zoxide_zi "$@" && ls
}
alias z=z_alias
alias zi=zi_alias

function srm {
    mv "$@" ~/.local/share/Trash/files
}

# Navigation
alias fcdf='cd $(find . -type d -print | fzf)'
